import express from "express";
import { isSeller } from "../middlewares/auth.middleware.js";
import { createProduct } from "../services/product.service.js";
const router = express.Router();
router.post("/product/create", isSeller, createProduct);
// router.get("/product/:id", getSingleProduct);
// router.get("/products", getProducts);
// router.put("/product/:id", editProduct);
// router.patch("/product/:id", editProductPart);
// router.delete("/product/delete", deleteProduct);
export default router;
